language: ruby
rvm:
- 2.1.1
env:
  global:
  - GIT_COMMITTER_NAME=nacyot
  - GIT_COMMITTER_EMAIL=propellerheaven@gmail.com
  - GIT_AUTHOR_NAME=nacyot
  - GIT_AUTHOR_EMAIL=propellerheaven@gmail.com
  - secure: XB6gBEcRiNPLzs+rlcBLB7DSAtKLvEl2l9NTt2+QsFt4I3LkR9icPbiCyK6LchmJlZcgaSunEn+H+zHHt8AEf4k0tFtRUQCwVNA3O16ZPJxKc/LM6KCg45fnUTxuLameKVBnRVTQdDiflWXTR1MM7Q6dkdKWOrZapH8kUPfSNzQ=
before_install:
  - sudo apt-get install -qq -y python-dev python-setuptools pandoc 
  - sudo pip install nose tornado jinja2 sphinx pyzmq
  - sudo pip install ipython
before_script:
  - npm install -g bower
  - yes no | bower install
  - git clone https://github.com/nacyot/blog.nacyot.com.git build
script:
  - bundle exec middleman build
after_success:
  - cd build
  - git add -A
  - git commit -m 'Update build files'
  - git push --quiet https://$GH_TOKEN@github.com/nacyot/blog.nacyot.com.git gh-pages
